title: "James Moorcroft Resume"
description: "City of Calgary Resume and Experience"
author: James Moorcroft
url: "https://jmoorcroft.github.io/resume"

theme: jekyll-theme-midnight
markdown: kramdown

