title: "James Moorcroft Resume"
description: "Hosted Markdown resume via GitHub Pages"
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
markdown: kramdown
author: James Moorcroft
url: "https://jmoorcroft.github.io/resume"

